name = "lunaxcode-cms"
main = "src/worker.ts"
compatibility_date = "2024-03-14"

[[ d1_databases ]]
binding = "DB"
database_name = "lunaxcode-cms"
database_id = "your-database-id-here"

[env.development]
[[ env.development.d1_databases ]]
binding = "DB"
database_name = "lunaxcode-cms-dev"
preview_database_id = "your-dev-database-id-here"